version: '3.4'
# Usage for any service
#   - Run shell inside container: docker-compose run --rm --service-ports SERVICE_NAME bash
services:
  react:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Same as $WORKDIR from Dockerfile
